### ISSUE TITLE
start page setting

### ISSUE THREAD

**Issue by otter66** [otter66/spring-board#4]
https://github.com/otter66/spring-board/blob/259487e4b15f8191df2c3fd166992a20806edeb6/board/src/main/webapp/WEB-INF/web.xml#L33

시작페이지 변경이 적용 되지 않는 것 같다.

**Comment by lemondkel** [comment]
https://admm.tistory.com/82

참고해보심이 좋을 것 같습니다.
webapps 밑의 경로를 다 입력해야 될 것 같기도 합니다.

**Comment by otter66** [comment]
말씀해주신 것처럼 경로 전체를 지정해주니 잘 작동합니다!!
감사합니다!! :)
